services:
  emby_medialinker:
    restart: always
    volumes:
    - ./data/medialinker:/opt
    environment:
    - AUTO_UPDATE=False
    - SERVER=emby
    - NGINX_PORT=8091
    #- NGINX_SSL_PORT=8095
    container_name: medialinker
    image: 'thsrite/medialinker:latest'
    ports:
    - 8091:8091 # HTTP port
    depends_on:
    - emby_server
    networks:
      custom_net:

  emby_server:
    image: amilys/embyserver:4.8.10.0
    #image: amilys/embyserver:4.9.0.43
    container_name: goembyserver
    hostname: goembyserver
    #runtime: nvidia # Expose NVIDIA GPUs
    #network_mode: host # Enable DLNA and Wake-on-Lan
    environment:
      - UID=0 # The UID to run emby as (default: 2)
      - GID=0 # The GID to run emby as (default 2)
      - GIDLIST=0 # A comma-separated list of additional GIDs to run emby as (default: 2)
    volumes:
      - /opt/backup/data/emby/emby/config:/config # Configuration directory
      - /opt/backup/data/emby/emby/cache:/cache # Configuration directory
      - /opt/backup/data/emby/autofilm/media:/media:rshared
    #ports:
    #- 127.0.0.1:8885:8096 # HTTP port
    #  - 8920:8920 # HTTPS port
    devices:
      - /dev/dri:/dev/dri # VAAPI/NVDEC/NVENC render nodes
      #- /dev/vchiq:/dev/vchiq # MMAL/OMX on Raspberry Pi
    restart: always
    networks:
      custom_net:
        ipv4_address: 10.5.0.5

  emby_telegram_webhook:
    container_name: emby_telegram_webhook
    build: ./data/dockerbuild/emby_telegram_webhook/
    environment:
    - FLASK_DEBUG=1
    volumes:
    - ./data/telegram-notifier:/config
    depends_on:
    - emby_server
    #ports:
    #- 5000:5000
    restart: always
    networks:
      custom_net:
        ipv4_address: 10.5.0.6

  emby_autoscan:
    build: ./data/dockerbuild/emby_autoscan
    container_name: emby_autoscan
    hostname: emby_autoscan
    command: ["python3", "/app/app.py", "/media/"]
    environment:
    - UID=0
    - GID=0
    - EMBY_URL=http://10.5.0.5:8096
    - EMBY_API_KEY=639b9b5d66a14c84a2a4545529d0225a
    - DATABASE_FILE=/app/db/emby_monitor.db
    volumes:
    - ./data/autoscan/:/app/db:rshared
    - /opt/backup/data/emby/autofilm/media:/media:rshared
    restart: always
    depends_on:
    - emby_server
    networks:
      custom_net:

  emby_autofilm:
    restart: always
    container_name: autofilm
    volumes:
    - ./data/autofilm/:/config
    - /opt/backup/data/emby/autofilm/media:/media
    - /opt/backup/data/emby/autofilm/logs:/logs
    #image: akimio/autofilm
    #image: x
    build: ./data/dockerbuild/AutoFilm
    networks:
      custom_net:




networks:
  custom_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          #gateway: 10.5.0.1


